### ISSUE TITLE
Runtime goes higher when increasing number of threads

### ISSUE THREAD

**Issue by AmIr-KinG** [gokcehan/pns#1]
Hi,

I have run your code with [this DIMAC file](http://lime.cs.elte.hu/~kpeter/data/mcf/netgen/netgen_8_10e.min.gz) using both 1 core and 8 cores. But the runtime increases instead of going down. Here is the output when using 1 core:

> OPENMP DISPLAY ENVIRONMENT BEGIN
  _OPENMP = '201511'
  OMP_DYNAMIC = 'FALSE'
  OMP_NESTED = 'FALSE'
  OMP_NUM_THREADS = '1'
  OMP_SCHEDULE = 'DYNAMIC,16'
  OMP_PROC_BIND = 'TRUE'
  OMP_PLACES = '{0:8}'
  OMP_STACKSIZE = '0'
  OMP_WAIT_POLICY = 'PASSIVE'
  OMP_THREAD_LIMIT = '4294967295'
  OMP_MAX_ACTIVE_LEVELS = '2147483647'
  OMP_CANCELLATION = 'FALSE'
  OMP_DEFAULT_DEVICE = '0'
  OMP_MAX_TASK_PRIORITY = '0'
  OMP_DISPLAY_AFFINITY = 'FALSE'
  OMP_AFFINITY_FORMAT = 'level %L thread %i affinity %A'
OPENMP DISPLAY ENVIRONMENT END
c pns v1.0.0
c # nodes             : 1024
c # arcs              : 8192
c # arcs in a block   : 96
c Init Time           : 6 ms
c # iterations        : 4930
c Time                : 6 ms
c - find entering arc : 2 ms (0.369128)
c - find join node    : 0 ms (0.106148)
c - find leaving arc  : 0 ms (0.141372)
c - change flows      : 0 ms (0.0219033)
c - change states     : 0 ms (0.0170054)
c - update tree       : 0 ms (0.104263)
c - update pots       : 0 ms (0.109992)
s 365288094

This is the output when using 8 cores:

> OPENMP DISPLAY ENVIRONMENT BEGIN
  _OPENMP = '201511'
  OMP_DYNAMIC = 'FALSE'
  OMP_NESTED = 'FALSE'
  OMP_NUM_THREADS = '8'
  OMP_SCHEDULE = 'DYNAMIC,16'
  OMP_PROC_BIND = 'TRUE'
  OMP_PLACES = '{0:8}'
  OMP_STACKSIZE = '0'
  OMP_WAIT_POLICY = 'PASSIVE'
  OMP_THREAD_LIMIT = '4294967295'
  OMP_MAX_ACTIVE_LEVELS = '2147483647'
  OMP_CANCELLATION = 'FALSE'
  OMP_DEFAULT_DEVICE = '0'
  OMP_MAX_TASK_PRIORITY = '0'
  OMP_DISPLAY_AFFINITY = 'FALSE'
  OMP_AFFINITY_FORMAT = 'level %L thread %i affinity %A'
OPENMP DISPLAY ENVIRONMENT END
c pns v1.0.0
c # nodes             : 1024
c # arcs              : 8192
c # arcs in a block   : 96
c Init Time           : 6 ms
c # iterations        : 4930
c Time                : 18 ms
c - find entering arc : 13 ms (0.746467)
c - find join node    : 0 ms (0.0446183)
c - find leaving arc  : 1 ms (0.0601861)
c - change flows      : 0 ms (0.00855522)
c - change states     : 0 ms (0.00622188)
c - update tree       : 0 ms (0.0417844)
c - update pots       : 0 ms (0.0424539)
s 365288094

As you can see the runtime increases from 6 ms (1 core) to 18 ms (8 cores). Below you can see the outputs of [a bigger DIMAC file](http://lime.cs.elte.hu/~kpeter/data/mcf/netgen/netgen_8_19a.min.gz).

> c pns v1.0.0
c # nodes             : 524288
c # arcs              : 4194304
c # arcs in a block   : 2048
c Init Time           : 1899 ms
c # iterations        : 1725245
c Time                : 51413 ms
c - find entering arc : 13043 ms (0.253702)
c - find join node    : 4770 ms (0.0927896)
c - find leaving arc  : 4363 ms (0.0848718)
c - change flows      : 58 ms (0.00113618)
c - change states     : 65 ms (0.00127279)
c - update tree       : 3581 ms (0.0696687)
c - update pots       : 25262 ms (0.491367)
s 12366225623

> c pns v1.0.0
c # nodes             : 524288
c # arcs              : 4194304
c # arcs in a block   : 2048
c Init Time           : 1941 ms
c # iterations        : 1723046
c Time                : 55253 ms
c - find entering arc : 7498 ms (0.135716)
c - find join node    : 5270 ms (0.0953809)
c - find leaving arc  : 5135 ms (0.0929504)
c - change flows      : 71 ms (0.00129573)
c - change states     : 70 ms (0.00127074)
c - update tree       : 4332 ms (0.0784042)
c - update pots       : 32591 ms (0.589846)
s 12366225623

The same thing has happened here. Could you please look into this matter?

**Comment by gokcehan** [comment]
@AmIr-KinG 

This is in accordance with the results presented in our submitted paper. We experimented with `netgen_8_20` and failed to get any speedups with any parameter combinations. Note, `netgen_8_20` is a relatively small (i.e. 8M arcs) sparse graph and it does not show a decreasing trend for the number of iterations with increasing block sizes. Our algorithm aims to provide a gain for much bigger dense graphs with up to a billion arcs. Our results in the paper show a positive speedup for all instances with more than 10M arcs. We also expect to have some positive speedups for `netgen_8` family of graphs with bigger sizes, though these may take a long time to be solved. These findings are discussed in detail in our submitted paper.
